# Generated by Django 4.2.2 on 2023-07-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_content_comment_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
        migrations.AddField(
            model_name='bid',
            name='comments',
            field=models.ManyToManyField(related_name='listings', to='auctions.comment'),
        ),
    ]
