# Generated by Django 4.2.2 on 2023-07-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_bid_comments_listing_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listing_id',
            field=models.ForeignKey(db_column='listing_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
            preserve_default=False,
        ),
    ]
