# Generated by Django 4.2.2 on 2023-07-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_comments_alter_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='created_by',
            new_name='creator',
        ),
    ]
