# Generated by Django 4.2.2 on 2023-07-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_listing_bids_listing_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='highest_bid',
        ),
    ]
