# Generated by Django 4.2.2 on 2023-07-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_highest_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='highest_bid',
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listing'),
        ),
    ]
