# Generated by Django 4.2.2 on 2023-07-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_rename_created_at_bid_timestamp_remove_listing_bids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_bids', to='auctions.bid'),
        ),
        migrations.AddField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(related_name='listings', to='auctions.comment'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
