# Generated by Django 4.2.2 on 2023-07-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_listing_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
    ]
